### ISSUE TITLE
[Contraption Framework] Random Error,

### ISSUE THREAD

**Issue by LegionInstaller** [ACF-Team/CFW#5]
[Contraption Framework] lua/cfw/classes/family_sv.lua:53: attempt to index local 'child' (a number value)
  1. Add - lua/cfw/classes/family_sv.lua:53
   2. create - lua/cfw/classes/family_sv.lua:17
    3. SetParent - lua/cfw/core/parenting_sv.lua:33
     4. unknown - gamemodes/sandbox/entities/effects/selection_indicator.lua:19

**Comment by KemGus** [comment]
I've got the same error, very annoying.
I've had a contraption spawned and I wasn't using it

**Comment by KemGus** [comment]
After that error occurs, using a weld tool on props makes these errors:
```
[armoredcombatextended] addons/armoredcombatextended/lua/cfw/extensions/ace_sv.lua:38: attempt to call field 'GetTable' (a nil value)
  1. v - addons/armoredcombatextended/lua/cfw/extensions/ace_sv.lua:38
   2. Run - lua/includes/modules/hook.lua:96
    3. Add - lua/cfw/classes/contraption_sv.lua:51
     4. connect - lua/cfw/core/connectivity_sv.lua:58
      5. SetParent - lua/cfw/core/parenting_sv.lua:25
       6. unknown - gamemodes/sandbox/entities/effects/selection_indicator.lua:19


[ERROR] gamemodes/sandbox/entities/effects/selection_indicator.lua:49: attempt to compare nil with number
  1. unknown - gamemodes/sandbox/entities/effects/selection_indicator.lua:49


[ERROR] gamemodes/sandbox/entities/effects/selection_indicator.lua:41: attempt to perform arithmetic on field 'Alpha' (a nil value)
  1. unknown - gamemodes/sandbox/entities/effects/selection_indicator.lua:41

```

**Comment by CheezusChrust** [comment]
After doing some experimenting, two things I've found:
- the Multi Parent/Unparent tool detours GetChildren, and it looks like CFW was written with that detour in mind
- On certain entities (base_anim??) GetChildren will return the expected numerically indexed table instead, causing the errors reported here

Tested by making the following modification in `families_sv.lua` in both `CLASS:Add` and `CLASS:Sub`
```lua
        for k, v in pairs(entity:GetChildren()) do
            local child = isnumber(k) and v or k
            if isnumber(k) then print("wtf", k, v) end
            ...
```

When spawning an affected contraption I see this in the console:
```
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
wtf	1	Entity [-1][base_anim]
```
