### ISSUE TITLE
"attempt to index local 'link' (a nil value)" when disconnecting E2 holograms

### ISSUE THREAD

**Issue by CheezusChrust** [ACF-Team/CFW#7]
Been seeing the error in the title near daily for quite a while now, and although I don't know exactly how to reproduce it, it seems to be related to E2 holograms in particular.

```
addons/cfw/lua/cfw/core/connectivity_sv.lua:65: attempt to index local 'link' (a nil value)
   1.  __index - [C]:-1
    2.  disconnect - addons/cfw/lua/cfw/core/connectivity_sv.lua:65
     3.  SetParent - addons/cfw/lua/cfw/core/parenting_sv.lua:24
      4.  SetParent - addons/acf-3-tyunge/lua/acf/contraption/contraption_sv.lua:253
       5.  Function - lua/autorun/parent_childtables.lua:26
        6.  fn - lua/includes/extensions/entity.lua:146
         7.  unknown - addons/ulib/lua/ulib/shared/hook.lua:109
```

Looking at the error logger, in every instance of this, `entA` is an E2 hologram.
```
indexB = Number [1159]
entA   = Entity [2335][gmod_wire_hologram]
```

**Comment by thecraftianman** [comment]
This is a particularly annoying issue that I've seen every once in a while on my own server. I think it could be something to do with certain entities being linked with a different index from the one that gets used to disconnect them. This can also occur with E2s and ACF-3 turret drives. I've tried to look into it myself but no luck so far

**Comment by thecraftianman** [comment]
Might've figured this one out; some chips like MPFC can try to parent holos to themselves, which causes issues later down the line when trying to disconnect them from a contraption (they attempt to disconnect themselves from...themselves...)

Not 100% sure if this is gonna definitively solve the issue but lmk if it still shows up
