### ISSUE TITLE
attempt to index field '_links' (a nil value)

### ISSUE THREAD

**Issue by brandonsturgeon** [ACF-Team/CFW#8]
I've seen this a couple of times today. Unfortunately I don't have any more context than these images:

[Relevant line](https://github.com/acf-team/cfw/blob/main/lua/cfw/classes/link_sv.lua#L70)

Something to do with sprites maybe?

![image](https://github.com/ACF-Team/CFW/assets/7936439/515630e5-4f0c-4107-8021-4a4f787ecd94)
![image](https://github.com/ACF-Team/CFW/assets/7936439/5669d8e6-0fc7-429d-b145-887e1ec09744)

**Comment by thecraftianman** [comment]
Think this might be closed by [7331e60](https://github.com/ACF-Team/CFW/commit/7331e604be11418902377b006cadd71d3482f2ae); lmk if it continues to show up after this or not

**Comment by brandonsturgeon** [comment]
Still seeing a bit of this.

Line 68 now, where `entA` is an `env_spritetrail`

**Comment by thecraftianman** [comment]
Alright, I'll take another look. Line 68 refers to entB, though; what are the locals for this particular instance of the error?

**Comment by brandonsturgeon** [comment]
Here's the exact error, and here's the [context](https://github.com/acf-team/cfw/blob/main/lua/cfw/core/connectivity_sv.lua#L68)
![image](https://github.com/ACF-Team/CFW/assets/7936439/9617cd5b-421e-44e0-993e-941bf879cc53)

**Comment by brandonsturgeon** [comment]
I believe this error may be related to this issue, as it's trying to loop over `_links` (also nil):

[(context)](https://github.com/acf-team/cfw/blob/main/lua/cfw/core/connectivity_sv.lua#L16)
![image](https://github.com/ACF-Team/CFW/assets/7936439/c4bd6179-8d29-4ff3-b30b-72c831fcbab0)

**Comment by TwistedTail** [comment]
I was wondering, should it really be necessary to consider entities without a physics object when creating a contraption? I'm pretty sure this problem and others could be related to that.

**Comment by brandonsturgeon** [comment]
I think if you want the library to be as useful as possible, I'd say yes.

For the purposes of ACF (and anything else I can personally think of right now), maybe not.

**Comment by TwistedTail** [comment]
I might have a defitive fix for it on #9

**Comment by TwistedTail** [comment]
Fixed on #9, closing.
